services:
  apache:
    image: php:8.2-apache
    container_name: lamp_apache
    restart: always
    volumes:
      - ./var/www/html:/var/www/html
      - ./ssh/authorized_keys:/root/.ssh/authorized_keys # Para acceso SSH
    ports:
      - "8880:80"
      - "2222:22" # Puerto SSH
    depends_on:
      - mysql
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    command: >
      bash -c "apt update &&
               apt install -y net-tools &&
               apt install -y openssh-server &&
               mkdir -p /run/sshd &&
               useradd -m -s /bin/bash dev &&
               echo 'dev:password' | chpasswd &&
               service ssh start &&
               apache2-foreground &&
               tail -f /dev/null"
    networks:
      lamp_network:
        ipv4_address: 172.100.0.10

  mysql:
    image: mysql:8.0
    container_name: lamp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      lamp_network:
        ipv4_address: 172.100.0.11

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: lamp_phpmyadmin
    restart: always
    ports:
      - "8180:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      lamp_network:
        ipv4_address: 172.100.0.12

volumes:
  mysql_data:


networks:
  lamp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24