services:
  nginx:
    image: nginx:latest
    container_name: nginx_server2
    networks:
      red_nginx:
        ipv4_address: 10.10.10.102
    ports:
      - "8082:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  red_nginx:
    external: true  # Usar una red creada con anterioridad
